import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans';
import './globals.css'
import Link from "next/link";
import Navigation from './Navigation';

export const metadata: Metadata = {
  title: 'Image Comparison',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} bg-gray-100`}>
        <div className="w-full max-w-lg mx-auto">
          <h2 className='text-center p-12 tracking-tight text-2xl font-bold'>Image Comparison</h2>
          <Navigation />
        </div>
        {children}
        <div className="w-full max-w-lg mx-auto text-center pb-10">
          <div>&copy; {new Date().getFullYear()}. <Link href="https://nextjs.org/docs/pages/api-reference/components/image" target="_blank">More on Next Image.</Link></div>
        </div>
      </body>
    </html>
  )
}
