import type { Metadata } from 'next'
import { GeistSans } from 'geist/font/sans';
// import { GeistMono } from 'geist/font/mono';
import './globals.css'

// const geist = GeistSans()

export const metadata: Metadata = {
  title: 'Image Comparison',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${GeistSans.className} bg-gray-100`}>{children}</body>
    </html>
  )
}
